shortDomain: xuanurl.herokuapp.com

logging:
    loggers:
        "com.xuan.urlshortener" : DEBUG

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080
