shortDomain: "localhost:8080"

logging:
    loggers:
        "com.xuan.urlshortener" : DEBUG

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080

database:
    driverClass: org.postgresql.Driver
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/urlshortener
    maxWaitForConnection: 1s
    validationQuery: "/* Health Check */ SELECT 1"
    validationQueryTimeout: 3s
    minSize: 1
    maxSize: 4
    initialSize: 1
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute
